--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/18/2024 8:20:40 AM
-- Server version: 8.3.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE qr_checkin;

--
-- Drop table `images`
--
DROP TABLE IF EXISTS images;

--
-- Drop table `event_categories`
--
DROP TABLE IF EXISTS event_categories;

--
-- Drop table `categories`
--
DROP TABLE IF EXISTS categories;

--
-- Drop table `devices`
--
DROP TABLE IF EXISTS devices;

--
-- Drop table `notifications`
--
DROP TABLE IF EXISTS notifications;

--
-- Drop table `registrations`
--
DROP TABLE IF EXISTS registrations;

--
-- Drop table `events`
--
DROP TABLE IF EXISTS events;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE qr_checkin;

--
-- Create table `users`
--
CREATE TABLE users (
  username varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  hash_password varchar(60) binary CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  role enum ('ROLE_user', 'ROLE_admin') NOT NULL DEFAULT 'ROLE_user',
  status enum ('ACTIVE', 'BANNED') NOT NULL DEFAULT 'ACTIVE',
  full_name varchar(120) binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  email varchar(50) binary CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  birthdate date DEFAULT NULL,
  sex bit(1) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (username)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX email (email);

--
-- Create table `events`
--
CREATE TABLE events (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  description longtext DEFAULT NULL,
  slots int UNSIGNED DEFAULT NULL,
  start_at timestamp NULL DEFAULT NULL,
  end_at timestamp NULL DEFAULT NULL,
  location varchar(255) binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  latitude decimal(9, 6) DEFAULT NULL,
  longitude decimal(9, 6) DEFAULT NULL,
  radius double NOT NULL,
  created_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at timestamp NULL DEFAULT NULL,
  deleted_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  is_required bit(1) NOT NULL DEFAULT b'0',
  is_approved bit(1) NOT NULL,
  checkin_qr_code varchar(64) NOT NULL,
  checkout_qr_code varchar(64) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `checkin_qr_code` on table `events`
--
ALTER TABLE events
ADD UNIQUE INDEX checkin_qr_code (checkin_qr_code);

--
-- Create index `checkout_qr_code` on table `events`
--
ALTER TABLE events
ADD UNIQUE INDEX checkout_qr_code (checkout_qr_code);

--
-- Create foreign key
--
ALTER TABLE events
ADD CONSTRAINT FK_events_created_by FOREIGN KEY (created_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE events
ADD CONSTRAINT FK_events_deleted_by FOREIGN KEY (deleted_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create table `registrations`
--
CREATE TABLE registrations (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  event_id bigint UNSIGNED NOT NULL,
  checked_in_at timestamp NULL DEFAULT NULL,
  checked_out_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  accepted_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at timestamp NULL DEFAULT NULL,
  deleted_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE registrations
ADD CONSTRAINT FK_registrations_event_id FOREIGN KEY (event_id)
REFERENCES events (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE registrations
ADD CONSTRAINT FK_tickets_deleted_by FOREIGN KEY (deleted_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create table `notifications`
--
CREATE TABLE notifications (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  eventId bigint UNSIGNED DEFAULT NULL,
  message varchar(255) binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  is_read bit(1) NOT NULL DEFAULT b'0',
  type enum ('CHECKIN', 'CHECKOUT', 'INVITATION', 'EVENT_UPDATE') NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE notifications
ADD CONSTRAINT FK_notifications_eventId FOREIGN KEY (eventId)
REFERENCES events (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE notifications
ADD CONSTRAINT FK_notifications_username FOREIGN KEY (username)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create table `devices`
--
CREATE TABLE devices (
  device_id varchar(64) NOT NULL,
  device_name varchar(255) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  username varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  refresh_token varchar(255) DEFAULT NULL,
  PRIMARY KEY (device_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `username` on table `devices`
--
ALTER TABLE devices
ADD UNIQUE INDEX username (username);

--
-- Create foreign key
--
ALTER TABLE devices
ADD CONSTRAINT FK_devices_username FOREIGN KEY (username)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create table `categories`
--
CREATE TABLE categories (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL DEFAULT 'utf8mb4_0900_ai_ci',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  deleted_by varchar(50) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE categories
ADD CONSTRAINT FK_categories_created_by FOREIGN KEY (created_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE categories
ADD CONSTRAINT FK_categories_deleted_by FOREIGN KEY (deleted_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE categories
ADD CONSTRAINT FK_categories_updated_by FOREIGN KEY (updated_by)
REFERENCES users (username) ON UPDATE CASCADE;

--
-- Create table `event_categories`
--
CREATE TABLE event_categories (
  eventId bigint UNSIGNED NOT NULL,
  categoryId int UNSIGNED NOT NULL,
  PRIMARY KEY (eventId, categoryId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE event_categories
ADD CONSTRAINT FK_event_categories_categoryId FOREIGN KEY (categoryId)
REFERENCES categories (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE event_categories
ADD CONSTRAINT FK_event_categories_eventId FOREIGN KEY (eventId)
REFERENCES events (id) ON UPDATE CASCADE;

--
-- Create table `images`
--
CREATE TABLE images (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  extension varchar(10) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT '',
  status bit(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('user001', '$2a$10$78mTBAJf6W5hR9JtuU3k0.DfKM73QThuNfNjYF.53fsvUP8FrZZAi', 'ROLE_user', 'ACTIVE', NULL, 'user001@gmail.com', NULL, NULL, '2024-04-09 01:52:54', '2024-04-09 01:52:54'),
('user002', '$2a$10$pFy60XNx24ml55jVlsFwi.5TlraNdI2/U8seeYt1Qte/aIscIxWNq', 'ROLE_user', 'ACTIVE', NULL, 'user002@gmail.com', NULL, NULL, '2024-04-15 03:24:53', '2024-04-15 03:24:53');

-- Table qr_checkin.events does not contain any data (it is empty)

-- Table qr_checkin.categories does not contain any data (it is empty)

-- Table qr_checkin.registrations does not contain any data (it is empty)

-- Table qr_checkin.notifications does not contain any data (it is empty)

-- Table qr_checkin.images does not contain any data (it is empty)

-- Table qr_checkin.event_categories does not contain any data (it is empty)

-- 
-- Dumping data for table devices
--
INSERT INTO devices VALUES
('UE1A.230829.036.A1', 'sdk_gphone64_x86_64', '2024-04-17 01:20:08', '2024-04-17 01:20:08', 'user002', 'eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV91c2VyIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoidXNlcjAwMiIsImlhdCI6MTcxMzI5MTYwNywiZXhwIjoxNzEzODk2NDA3fQ.qzdNkrLPFNQeOcMT9eSX3Fzhnkz-KNqvic0H3AkGimg'),
('UP1A.231005.007', 'SM-M146B', '2024-04-10 01:28:28', '2024-04-17 21:23:03', 'user001', 'eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV91c2VyIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoidXNlcjAwMSIsImlhdCI6MTcxMzM2Mzc4MiwiZXhwIjoxNzEzOTY4NTgyfQ.LHoZDAIF44yP0r8-7YhaaZ4ryctm-Fvg6UmQRWTtnec');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;